<?php 
$title = 'Videos';
$this->headTitle($title);
$videos = $this->videos;
?>
<div class="row">
	<!-- Left col -->
	<section class="col-lg-7">
		<div>
			<!-- main sub page content// -->

			<div class="panel-default">
				<div class="panel-heading">
					<i class="fa fa-youtube-play"></i> Newest Videos
				</div>
				<div class="panel-body">
					<div class="box-body">
					
					<?php foreach ($videos as $v):?>
		              <div class="col-sm-6 col-md-4">
							<div class="thumbnail">
								<a href="<?php echo $this->url('videos',array('action'=>'play','id'=>$v->id))?>"><img src="<?php echo $v->thumbnail; ?>"
									alt="..."></a>
								<div class="runtime">
									<span><?php echo $v->runtime;?></span>
								</div>
								<div class="caption">
									<h3><?php echo $v->title?></h3>
									<p><?php echo $v->desc;?></p>
									<p></p>
								</div>
							</div>
						</div>
                    <?php endforeach;?>
					</div>


				</div>
			</div>

		</div>

	</section>
	<!-- /.Left col -->

	<!-- right col (We are only adding the ID to make the widgets sortable)-->
	<section class="col-lg-5 connectedSortable">

		<div class="panel-default">
			<div class="panel-heading">
				<i class="fa  fa-bookmark"></i> Videos Ads
			</div>
			<div class="panel-body rightbar-menu">
				<!-- right navigation //-->
              <?php echo $this->render('layout/newvideos') ?>
			</div>
		</div>
	</section>

</div>