
<div class="row">
	<!-- Left col -->
	<section class="col-lg-7">
		<div>
			<!-- main sub page content// -->

			<div class="panel-default">
				<div class="panel-heading"><i class="fa fa-youtube-play"></i> Newest Videos</div>
				<div class="panel-body">
					<div class="box-body">


  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <img src="/img/thumbnails/vids/sample320x200-1.png" alt="...">
      <div class="caption">
        <h3>Thumbnail label</h3>
        <p>The quick brown fox jumps over the lazy dog</p>
        <p></p>
      </div>
    </div>
  </div>
  
  
    <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <img src="/img/thumbnails/vids/sample320x200.png" alt="...">
      <div class="caption">
        <h3>Thumbnail label</h3>
        <p>The quick brown fox jumps over the lazy dog</p>
        <p></p>
      </div>
    </div>
  </div>
  
  
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <img src="/img/thumbnails/vids/sample320x200-1.png" alt="...">
      <div class="caption">
        <h3>Thumbnail label</h3>
        <p>The quick brown fox jumps over the lazy dog</p>
        <p></p>
      </div>
    </div>
  </div>
  
  
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <img src="/img/thumbnails/vids/sample320x200.png" alt="...">
      <div class="caption">
        <h3>Thumbnail label</h3>
        <p>The quick brown fox jumps over the lazy dog</p>
       
      </div>
    </div>
  </div>

  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <img src="/img/thumbnails/vids/sample320x200-2.png" alt="...">
      <div class="caption">
        <h3>Thumbnail label</h3>
        <p>The quick brown fox jumps over the lazy dog</p>
        
      </div>
    </div>
  </div>
  
    <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <img src="/img/thumbnails/vids/sample320x200-3.png" alt="...">
      <div class="caption">
        <h3>Thumbnail label</h3>
        <p>The quick brown fox jumps over the lazy dog</p>
       
      </div>
    </div>
  </div>
  
      <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <img src="/img/thumbnails/vids/sample320x200-3.png" alt="...">
      <div class="caption">
        <h3>Thumbnail label</h3>
        <p>The quick brown fox jumps over the lazy dog</p>
       
      </div>
    </div>
  </div>
  
      <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <img src="/img/thumbnails/vids/sample320x200.png" alt="...">
      <div class="caption">
        <h3>Thumbnail label</h3>
        <p>The quick brown fox jumps over the lazy dog</p>
       
      </div>
    </div>
  </div>
  
        <div class="col-sm-6 col-md-5">
    <div class="thumbnail">
      <img src="/img/thumbnails/vids/sample320x200.png" alt="...">
      <div class="caption">
        <h3>Thumbnail label</h3>
        <p>The quick brown fox jumps over the lazy dog</p>
       
      </div>
    </div>
  </div>
  
						
					</div>


				</div>
			</div>

		</div>

	</section>
	<!-- /.Left col -->

	<!-- right col (We are only adding the ID to make the widgets sortable)-->
	<section class="col-lg-5 connectedSortable">

		<div class="panel-default">
			<div class="panel-heading"><i class="fa  fa-bookmark"></i> Videos Ads</div>
			<div class="panel-body rightbar-menu">
				<!-- right navigation //-->
              <?php echo $this->render('layout/newvideos') ?>
			</div>
		</div>
	</section>

</div>