<?php 
$title = 'Now Playing:: '.$this->playVideo->title;
$this->headTitle($this->playVideo->title);
$video = $this->playVideo;
?>
<div class="row">
	<!-- Left col -->
	<section class="col-lg-7">
		<div>
			<!-- main sub page content// -->

			<div class="panel-default">
				<div class="panel-heading">
				<h5><i class="fa fa-youtube-play"></i> <?php echo $this->escapeHtml($title); ?></h5>
				</div>
				<div class="panel-body">
					<div class="box-body">
			
                    <?php echo $video->embed_code;?>
					
					</div>
			</div>

		</div>

	</section>
	<!-- /.Left col -->

	<!-- right col (We are only adding the ID to make the widgets sortable)-->
	<section class="col-lg-5 connectedSortable">

		<div class="panel-default">
			<div class="panel-heading">
				<i class="fa  fa-bookmark"></i> Videos Ads
			</div>
			<div class="panel-body rightbar-menu">
				<!-- right navigation //-->
              <?php echo $this->render('layout/newvideos') ?>
			</div>
		</div>
	</section>

</div>