<div class="row">
	<!-- Left col -->
	<section class="col-lg-7">
		<div>
			<!-- main sub page content// -->

			<div class="panel-default">
				<div class="panel-heading">
					<i class="fa fa-youtube-play"></i> Newest Videos
				</div>
				<div class="panel-body">
					<div class="box-body">
					<iframe width="560" height="315" src="//www.youtube.com/embed/b1DzRb4DHGw" frameborder="0" allowfullscreen></iframe>
					
					


					
					</div>
			</div>

		</div>

	</section>
	<!-- /.Left col -->

	<!-- right col (We are only adding the ID to make the widgets sortable)-->
	<section class="col-lg-5 connectedSortable">

		<div class="panel-default">
			<div class="panel-heading">
				<i class="fa  fa-bookmark"></i> Videos Ads
			</div>
			<div class="panel-body rightbar-menu">
				<!-- right navigation //-->
              <?php echo $this->render('layout/newvideos') ?>
			</div>
		</div>
	</section>

</div>