<?php 
$title = 'Videos';
$this->headTitle($title);
$videos = $this->videos;


function dateDiff($time1, $time2, $precision = 6) {
	// If not numeric then convert texts to unix timestamps
	if (!is_int($time1)) {
		$time1 = strtotime($time1);
	}
	if (!is_int($time2)) {
		$time2 = strtotime($time2);
	}

	// If time1 is bigger than time2
	// Then swap time1 and time2
	if ($time1 > $time2) {
		$ttime = $time1;
		$time1 = $time2;
		$time2 = $ttime;
	}

	// Set up intervals and diffs arrays
	$intervals = array('year','month','day','hour','minute','second');
	$diffs = array();

	// Loop thru all intervals
	foreach ($intervals as $interval) {
		// Create temp time from time1 and interval
		$ttime = strtotime('+1 ' . $interval, $time1);
		// Set initial values
		$add = 1;
		$looped = 0;
		// Loop until temp time is smaller than time2
		while ($time2 >= $ttime) {
			// Create new temp time from time1 and interval
			$add++;
			$ttime = strtotime("+" . $add . " " . $interval, $time1);
			$looped++;
		}

		$time1 = strtotime("+" . $looped . " " . $interval, $time1);
		$diffs[$interval] = $looped;
	}

	$count = 0;
	$times = array();
	// Loop thru all diffs
	foreach ($diffs as $interval => $value) {
		// Break if we have needed precission
		if ($count >= $precision) {
			break;
		}
		// Add value and interval
		// if value is bigger than 0
		if ($value > 0) {
			// Add s if value is not 1
			if ($value != 1) {
				$interval .= "s";
			}
			// Add value and interval to times array
			$times[] = $value . " " . $interval;
			$count++;
		}
	}

	// Return string with times
	//return implode(", ", $times);
	return   $times[0];
}

function truncate($string,$length=100,$append="&hellip;") {
	$string = trim($string);

	if(strlen($string) > $length) {
		$string = wordwrap($string, $length);
		$string = explode("\n", $string, 2);
		$string = $string[0] . $append;
	}

	return $string;
}
?>
<div class="row">
	<!-- Left col -->
	<section class="col-lg-7">
		<div>
			<!-- main sub page content// -->

			<div class="panel-default">
				<div class="panel-heading">
					<i class="fa fa-youtube-play"></i> Newest Videos
				</div>
				<div class="panel-body">
					<div class="box-body">
					
					<?php foreach ($videos as $v):?>
		              <div class="col-sm-6">
							<div class="thumbnail">
								<a href="<?php echo $this->url('videos',array('action'=>'play','id'=>$v->id))?>"><img src="<?php echo $v->thumbnail; ?>"
									width="100%" height="100%" alt="..."></a>
								<div class="runtime">
									<span class="badge"><?php echo $v->runtime;?></span>
								</div>
								<h4><b><?php echo truncate($v->title,21)?></b></h4>
									<?php echo truncate($v->desc,23);?>
									<br/>
									<?php $rate = number_format( $v->rate / 5 );?>
									<b>Rate: </b><div class="basic" data-average="<?php echo $rate ?>" data-id="<?php $v->id ?>"></div>  <?php echo number_format($v->rate).'%'; ?>
									<br/>
									<b>Category: </b><a href="<?php echo  $this->url('videos',array('action'=>'videos-by-category','id'=>$v->cat_id))?>"><?php echo $v->cat_name?></a>
									<br/>
									<b>Views: </b> <?php echo $v->views?>
									<br/>
									<strong>Added: </strong> <?php echo dateDiff("now", $v->uploaded) ?>
							</div>
						</div>
                    <?php endforeach;?>
					</div>


				</div>
			</div>

		</div>

	</section>
	<!-- /.Left col -->

	<!-- right col (We are only adding the ID to make the widgets sortable)-->
	<section class="col-lg-5 connectedSortable">

		<div class="panel-default">
			<div class="panel-heading">
				<i class="fa  fa-bookmark"></i> Videos Ads
			</div>
			<div class="panel-body rightbar-menu">
				<!-- right navigation //-->
              <?php echo $this->render('layout/newvideos') ?>
			</div>
		</div>
	</section>

</div>