<?php echo $this->render('flashmessenger/layout');

$category = $this->categoryList;
?>
<div class="row">

	<!-- Left col -->
	<section class="col-lg-7 connectedSortable">
		<div>
			<!-- main sub page content// -->

			<div class="panel panel-default">
				<div class="panel-heading">Edit Video Categories</div>
				<div class="panel-body">

					<div class="box-body">
						<div class="row">
							<div class="col-xs-12">
								<div class="box">
									<div class="box-header">
										<h3 class="box-title">Video Category List</h3>
										<div class="box-tools">
											<div class="input-group">
												<input type="text" name="table_search"
													class="form-control input-sm pull-right"
													style="width: 150px;" placeholder="Search">
												<div class="input-group-btn">
													<button class="btn btn-sm btn-default">
														<i class="fa fa-search"></i>
													</button>
												</div>
											</div>
										</div>
									</div>
									<!-- /.box-header -->
									<div class="box-body table-responsive no-padding">
										<table class="table table-hover">
											<tbody>
												<tr>
													<th>ID</th>
													<th>Category Name</th>
													<th>Options</th>
												</tr>
												<?php foreach ($category as $c):?>
												<tr>
													<td><?php echo $c->id?></td>
													<td><?php echo $c->category_name?></td>
													<td><a href="<?php echo $this->url('admin',array('action'=>'edit-video-category','id'=>$c->id))?>"><i class="fa  fa-pencil"></i></a> | <a href="#"><i class="fa fa-times"></i></a></td>
												</tr>
												<?php endforeach;?>
											</tbody>
										</table>
									</div>
									<!-- /.box-body -->
								</div>
								<!-- /.box -->
							</div>
						</div>

					</div>
	
	</section>
	<!-- /.Left col -->

	<!-- right col (We are only adding the ID to make the widgets sortable)-->
	<section class="col-lg-5 connectedSortable">

		<div class="panel panel-default">
			<div class="panel-heading">Category Menu</div>
			<div class="panel-body rightbar-menu">
				<!-- right navigation //-->
    <?php echo $this->render('layout/menu') ?>
			</div>
		</div>
	</section>

</div>