<?php 
$title = 'Videos Online';
$this->headTitle($title);
$videos = $this->videos;
?>
<?php echo $this->render('flashmessenger/layout') ?>
<div class="row">

	<!-- Left col -->
	<section class="col-lg-7 connectedSortable">
		<div>
			<!-- main sub page content// -->

			<div class="panel panel-default">
				<div class="panel-heading">Videos</div>
				<div class="panel-body">

					<div class="box-body">
						<div class="row">
							<div class="col-xs-12">
								<div class="box">
									<div class="box-header">
										<h3 class="box-title">Video List</h3>
										<div class="box-tools">
											<div class="input-group">
												<input type="text" name="table_search"
													class="form-control input-sm pull-right"
													style="width: 150px;" placeholder="Search" />
												<div class="input-group-btn">
													<button class="btn btn-sm btn-default">
														<i class="fa fa-search"></i>
													</button>
												</div>
											</div>
										</div>
									</div>
									<!-- /.box-header -->
									<div class="box-body table-responsive no-padding">
										<table class="table table-hover">
											<tr>
												<th>id</th>
												<th>thumbnail</th>
												<th>upload</th>
												<th>views</th>
												<th>category</th>
												<th>published?</th>
												<th>options</th>
											</tr>
											<?php foreach ($videos as $v):?>
											<?php //process thumbnail 
                     $tmbnail = '/img/thumbnails/'.str_replace(ROOT_PATH."/data/", "", $v->thumbnail); 
                    ?>
                    
											<tr>
												<td><?php echo $v->id ?></td>
												<td>
												   <div class="">
														<div class="thumbnail">
															<a href="<?php echo $this->url('admin',array('action'=>'admin-edit-video','id'=>$v->id));?>"><img src="<?php echo $tmbnail;?>" width="100%" height="100%"
																alt="<?php echo $v->title; ?>"></a>
															<div class="runtime">
																<span class="badge"><?php echo $v->runtime;?></span>
															</div>
														</div>
													</div>
												</td>
												<td><?php  echo date("m/d/y g:i A", strtotime($v->uploaded));?></td>
												<td><?php echo $v->views;?></td>
												<td><?php echo $v->cat_name;?></td>
												<td><span class="label <?php echo ($v->publish)? "label-success":"label-danger"?>"><?php echo ($v->publish)? "live":"inactive"; ?></span></td>
												<td><a href=""><i class="fa fa-times" title="delete"></i></a> | <a href="<?php echo $this->url('admin',array('action'=>'admin-edit-video','id'=>$v->id));?>"><i class="fa fa-pencil" title="update"></i></a> | <a href=""><i class="fa fa-rotate-left" title="re-upload"></i></a></td>
											</tr>
											<?php endforeach;?>
																					
										</table>
									</div>
									<!-- /.box-body -->
									
									
									
																<!-- pagination -->
						<?php
// add at the end of the file after the table
echo $this->paginationControl (
		// the paginator object
		$videos,
		// the scrolling style; see http://zf2.readthedocs.org/en/release-2.1.4/modules/zend.paginator.usage.html#rendering-pages-with-view-scripts
		'Jumping',
		// the partial to use to render the control
		array (
				'partial/admin-video-paginator.phtml',
				'admin'
		),
		// the route to link to when a user clicks a control link
		array (
				'route' => 'admin',
		) ); ?>

								</div>
								<!-- /.box -->
							</div>


						</div>
					</div>

				</div>
	
	</section>
	<!-- /.Left col -->

	<!-- right col (We are only adding the ID to make the widgets sortable)-->
	<section class="col-lg-5 connectedSortable">

		<div class="panel panel-default">
			<div class="panel-heading">Menu</div>
			<div class="panel-body rightbar-menu">
				<!-- right navigation //-->
        <?php echo $this->render('layout/menu') ?>
		</div>
		</div>
	</section>

</div>