<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
 <?php echo $this->headTitle('Welcome to the newest '. $this->translate('Videos '))->setSeparator(' - ')->setAutoEscape(false) ?>
<meta
	content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no'
	name='viewport'>
	
	
	<link href="http://vjs.zencdn.net/4.10/video-js.css" rel="stylesheet">
<script src="http://vjs.zencdn.net/4.10/video.js"></script>
<style type="text/css">
  .vjs-default-skin { color: #ffffff; }
  .vjs-default-skin .vjs-play-progress,
  .vjs-default-skin .vjs-volume-level { background-color: #c5307f }
  .vjs-default-skin .vjs-control-bar,
  .vjs-default-skin .vjs-big-play-button { background: rgba(11,11,11,0.7) }
  .vjs-default-skin .vjs-slider { background: rgba(11,11,11,0.2333333333333333) }
  .vjs-default-skin .vjs-control-bar { font-size: 109% }
  
  .video-js {padding-top: 56.25%}
.vjs-fullscreen {padding-top: 0px}
</style>

<link href="/css/custom.css" rel="stylesheet" type="text/css" />
<!-- bootstrap 3.0.2 -->
<link href="/css/bootstrap.css" rel="stylesheet" type="text/css" />
<!-- font Awesome -->
<link href="/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
<!-- Ionicons -->
<link href="/css/ionicons.min.css" rel="stylesheet" type="text/css" />
<!-- Morris chart -->
<link href="/css/morris/morris.css" rel="stylesheet" type="text/css" />
<!-- jvectormap -->
<link href="/css/jvectormap/jquery-jvectormap-1.2.2.css"
	rel="stylesheet" type="text/css" />
<!-- Date Picker -->
<link href="/css/datepicker/datepicker3.css" rel="stylesheet"
	type="text/css" />
<!-- Daterange picker -->
<link href="/css/daterangepicker/daterangepicker-bs3.css"
	rel="stylesheet" type="text/css" />
<!-- bootstrap wysihtml5 - text editor -->
<link href="/css/jRating.jquery.css"
	rel="stylesheet" type="text/css" />
<!-- Theme style -->
<link href="/css/AdminLTE.css" rel="stylesheet" type="text/css" />
<link href="/css/AdminLTE.css" rel="stylesheet" type="text/css" />
<link href="/css/AdminLTE.css" rel="stylesheet" type="text/css" />

<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
          <script src="https://oss.maxcdn.com/libs/respond./js/1.3.0/respond.min.js"></script>
        <![endif]-->
</head>
<body class="skin-x">
	<!-- header logo: style can be found in header.less -->
	<header class="header">
        
        <?php  $url = $this->url('home');
         ?>
            <a href="<?php echo $url ?>" class="logo"> <!-- Add the class icon to your logo image or logo icon to add the margining -->
			
			<i class="fa  fa-play-circle-o"></i>XPedler
		</a>
		<!-- Header Navbar: style can be found in header.less -->
		<nav class="navbar navbar-static-top" role="navigation">
			<!-- Sidebar toggle button-->
			<a href="#" class="navbar-btn sidebar-toggle" data-toggle="offcanvas"
				role="button"> <span class="sr-only">Toggle navigation</span> <span
				class="icon-bar"></span> <span class="icon-bar"></span> <span
				class="icon-bar"></span>
			</a>
			
			
			
							<!-- search form -->
				<form action="#" method="get" class="sidebar-form">
					<div class="input-group">
						<input type="text" name="q" class="form-control"
							placeholder="Search..." /> <span class="input-group-btn">
							<button type='submit' name='seach' id='search-btn'
								class="btn btn-flat">
								<i class="fa fa-search"></i>
							</button>
						</span>
					</div>
				</form>
				<!-- /.search form -->
				
				
				
			<div class="navbar-right">
			
			</div>
		</nav>
	</header>
	<div class="wrapper row-offcanvas row-offcanvas-left">
		<!-- Left side column. contains the logo and sidebar -->
		<aside class="left-side sidebar-offcanvas">
			<!-- sidebar: style can be found in sidebar.less -->
			<section class="sidebar">
				<!-- Sidebar user panel -->
	

				<!-- sidebar menu: : style can be found in sidebar.less -->
				<ul class="sidebar-menu">
                    <?php 
                    

                    echo $this->navigation('navigation')
                    ->menu()
                    ->setPartial('partial/sidebar')
                  
                    ->render();
                                 
                    ?>
                    </ul>
			</section>
			<!-- /.sidebar -->
		</aside>


		<!-- Right side column. Contains the navbar and content of the page -->
		<aside class="right-side">
			<!-- Content Header (Page header) -->
	        <?php 
// 	        echo $this->navigation('navigation')->breadcrumbs()
//                                                       ->setMinDepth(0)
//                                                       ->setMaxDepth(2)
//                                                       ->setPartial('partial/breadcrumb');
	        
	        
	        
            ?>

			<!-- Main content -->
			<section class="content">
			


			     <?php echo $this->content; ?>
			     
			    
			
			</section>
			<!-- /.content -->
		</aside>
		<!-- /.right-side -->
	</div>
	<!-- ./wrapper -->


	<!-- jQuery 2.0.2 -->
	<script
		src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
	<!-- jQuery UI 1.10.3 -->
	<script src="/js/jquery-ui-1.10.3.min.js" type="text/javascript"></script>
	<!-- Bootstrap -->
	<script src="/js/bootstrap.min.js" type="text/javascript"></script>
	<!-- jvectormap -->
	<script src="/js/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js"
		type="text/javascript"></script>
	<script src="/js/plugins/jvectormap/jquery-jvectormap-world-mill-en.js"
		type="text/javascript"></script>
	<!-- jQuery Knob Chart -->
	<script src="/js/plugins/jqueryKnob/jquery.knob.js"
		type="text/javascript"></script>
	<!-- daterangepicker -->
	<script src="/js/plugins/daterangepicker/daterangepicker.js"
		type="text/javascript"></script>
	<!-- datepicker -->
	<script src="/js/plugins/datepicker/bootstrap-datepicker.js"
		type="text/javascript"></script>
		
		
			<!-- rating script -->
	<script src="/js/jRating.jquery.js"
		type="text/javascript"></script>

	<!-- iCheck -->
	<script src="/js/plugins/iCheck/icheck.min.js" type="text/javascript"></script>
	
	<!-- InputMask -->
    <script src="/js/plugins/input-mask/jquery.inputmask.js" type="text/javascript"></script>
    <script src="/js/plugins/input-mask/jquery.inputmask.date.extensions.js" type="text/javascript"></script>
    <script src="/js/plugins/input-mask/jquery.inputmask.extensions.js" type="text/javascript"></script>
        
	<!-- AdminLTE App -->
	<script src="/js/AdminLTE/app.js" type="text/javascript"></script>

	<!-- AdminLTE dashboard demo (This is only for demo purposes) 
	<script src="/js/AdminLTE/dashboard.js" type="text/javascript"></script>-->

	<!-- AdminLTE for demo purposes 
	<script src="/js/AdminLTE/demo.js" type="text/javascript"></script>-->
	
	<!-- Custon Js -->
   <script src="/js/custom.js" type="text/javascript"></script>

</body>
</html>